package constants

// AllowedOrigins ...
const AllowedOrigins = "ALLOWED_ORIGINS"

// Environment ...
const Environment = "ENVIRONMENT"

// HerokuPort ...
const HerokuPort = "PORT"

// LincolnPort ...
const LincolnPort = "LINCOLN_PORT"

// LincolnAddress ...
const LincolnAddress = "LINCOLN_ADDRESS"

// LincolnWriteTimeout ...
const LincolnWriteTimeout = "LINCOLN_WRITE_TIMEOUT"

// LincolnReadTimeout ...
const LincolnReadTimeout = "LINCOLN_READ_TIMEOUT"

// LincolnIdleTimeout ...
const LincolnIdleTimeout = "LINCOLN_IDLE_TIMEOUT"
